# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "compiled-regex"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
hex = "0.4.3"
regex-syntax = "0.6.28"
sha2 = "0.10.6"

