[package]
name = "compiled-regex-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
compiled-regex = { path = "../../" }
regex = "1.8.1"
